### ISSUE TITLE
Nothing workes

### ISSUE THREAD

**Issue by limelect** [tinyBigGAMES/PiroGameToolkit#2]
Is it a jok?

**Comment by jarroddavis6889** [comment]
There have been no releases yet. I'm currently working on examples and docs.

**Comment by jarroddavis6889** [comment]
Ok, I started pushing up Piro builds. You can always grab the latest daily development build here:
https://pirogametoolkit.com/download/file.php?name=PGT-Dev.zip
Note: It's still very much work-in-progress at this point, but what I got working should be stable.
