### ISSUE TITLE
Your example error

### ISSUE THREAD

**Issue by limelect** [tinyBigGAMES/PiroGameToolkit#3]
Compiling example with D10.2.3
 TBaseInterface = class(TNoRefCountObject, IBaseInterface)
TNoRefCountObject error cannot find

Also running your exe errors

**Comment by jarroddavis6889** [comment]
Hi, thanks for reporting.

1. What type of errors are you gettings?
2. Add `System.Generics.Defaults` in the uses section in PiroGameToolkit.pas
3. Add the following above `{ TBaseInterface }` line in PiroGameToolkit.pas:
```Pascal
{$if CompilerVersion < 35}
  // Delphi Delphi 10.4 or less
  TNoRefCountObject = TSingletonImplementation
{$ifend}
```
