### ISSUE TITLE
When run error

### ISSUE THREAD

**Issue by limelect** [tinyBigGAMES/PiroGameToolkit#4]
Ok now it compiles
but when run I open titled bitmap then
in procedure PiroRunGame(aGame: TBaseGameClass);
 LGame.Run; then
procedure TBaseGameApp.Run;
begin
  OnSetSettings(Settings);
  FGameEvent.SleepDelay := Settings.SleepDelay;
  inherited; <<<<<<<<<<<<<<<<<  On that
end;

i go to  Piro.RunGame(@FGameEvent); then
![Screenshot - 25_11_2021 , 16_23_17](https://user-images.githubusercontent.com/4199131/143458696-27663840-a674-498b-a992-bdd2190bb296.jpg)

**Comment by jarroddavis6889** [comment]
Hmm, interesting.
- What version of windows are you using (must be 10 or higher, 64 bits)
- You can only build win64 exes with Piro
- Create a new console application, and just add PiroRunGame(TBaseGameApp) and see if that works.
- Remember, to add win64 platform, will can compile/run as win32 application.

**Comment by jarroddavis6889** [comment]
Make sure PGT.dll is being found. This is DLL needs to be in the same folder as the EXEs.

**Comment by limelect** [comment]
Dll is there
window 7.
I give up.
Good luck

**Comment by jarroddavis6889** [comment]
Windows 7, that is the problem. As stated in all the README.md and by me in this post, you must be on Windows 10 or higher. It's built against the Windows 10 SDK so the win32 API calls won't work on Windows 7. Sorry bro.
